import InfoPageLayout from "@/components/InfoPageLayout";

export const metadata = { title:"Legal Notice — CrestCapital" };

export default function LegalPage() {
  return (
    <InfoPageLayout title="Legal Notice" subtitle="Important legal information about CrestCapital Ltd.">

      <h2>Company Information</h2>
      <p><strong>CrestCapital Ltd</strong><br/>
      Registered Office: Route d'Esch 69, L-1470 Luxembourg City, Luxembourg<br/>
      Email: <a href="mailto:legal@crestcapital.com">legal@crestcapital.com</a></p>

      <h2>Regulatory Status</h2>
      <p>CrestCapital Ltd is registered as a digital investment services company in Luxembourg. We operate in compliance with applicable Luxembourg and EU financial regulations. Our operations are subject to ongoing regulatory oversight.</p>

      <h2>Investment Risk Disclosure</h2>
      <p>All investments involve risk. The value of your investment may go down as well as up. Returns generated by CrestCapital's investment plans are based on historical performance of our diversified portfolio strategies, including AI-driven trading, digital assets, and real estate.</p>
      <p><strong>Past performance is not a guarantee of future results.</strong> You should not invest money you cannot afford to lose.</p>

      <h2>Cryptocurrency Risk</h2>
      <p>CrestCapital accepts and processes deposits and withdrawals in cryptocurrencies. Cryptocurrency values are highly volatile. CrestCapital is not responsible for fluctuations in the value of cryptocurrencies between the time of deposit and any subsequent conversion.</p>

      <h2>Jurisdiction & Governing Law</h2>
      <p>These legal notices and all use of the CrestCapital platform are governed by the laws of the Grand Duchy of Luxembourg. Any disputes arising from the use of our platform shall be subject to the exclusive jurisdiction of the Luxembourg courts, with arbitration proceedings to be conducted in Luxembourg City, Luxembourg.</p>

      <h2>Intellectual Property</h2>
      <p>All content on the CrestCapital platform — including text, graphics, logos, interfaces, and software — is the exclusive property of CrestCapital Ltd and is protected by intellectual property laws. Reproduction, distribution, or use of any content without express written permission is prohibited.</p>

      <h2>Limitation of Liability</h2>
      <p>To the fullest extent permitted by applicable law, CrestCapital Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of, or inability to use, the platform.</p>
      <p>Our total cumulative liability to you for any claim shall not exceed the total amount invested in your account at the time of the incident giving rise to the claim.</p>

      <h2>Force Majeure</h2>
      <p>CrestCapital shall not be held liable for any failure or delay in performance due to circumstances beyond our reasonable control, including but not limited to: natural disasters, government actions, network outages, cyberattacks, or cryptocurrency exchange failures.</p>

      <h2>Amendments</h2>
      <p>CrestCapital reserves the right to amend this Legal Notice at any time. Changes will be effective immediately upon publication on this page. Continued use of the platform constitutes acceptance of the amended notice.</p>

      <h2>Contact</h2>
      <p>For legal enquiries: <a href="mailto:legal@crestcapital.com">legal@crestcapital.com</a></p>

    </InfoPageLayout>
  );
}
